### PR TITLE
Mock PR to initiate CI service

### PR DESCRIPTION
**Pull request by rexagod**

### CODE REVIEW

**Comment by rexagod** [comment]
For some reason the token's empty https://travis-ci.com/publiclab/matcher-cli/jobs/209094455#L488

**Comment by rexagod** [comment]
<h3> Travis logs </h3> <pre> Event:pull_request <br/> ID:547530792 <br/> Job Number:30.1 <br/> VSnapLink:https://i.imgur.com/V4WvZ8y.png </pre> <br/>

**Comment by rexagod** [comment]
<h3> Travis logs </h3> <pre> Event:pull_request <br/> ID:547530793 <br/> Job Number:30.2 <br/> VSnapLink:https://i.imgur.com/JyHxx6w.png </pre> <br/>

**Comment by rexagod** [comment]
<h3> Travis logs </h3> <pre> Event:pull_request <br/> ID:209156520 <br/> Job Number:14.1 <br/> VSnapLink:https://i.imgur.com/zNg7PjV.png </pre> <br/>

**Comment by rexagod** [comment]
<h3> Travis logs </h3> <pre> Event:pull_request <br/> ID:547530794 <br/> Job Number:30.3 <br/> VSnapLink:https://i.imgur.com/7B1jNAo.png </pre> <br/>

**Comment by rexagod** [comment]
<h3> Travis logs </h3> <pre> Event:pull_request <br/> ID:209156522 <br/> Job Number:14.3 <br/> VSnapLink:https://i.imgur.com/Sh1Gi2y.png </pre> <br/>

**Comment by rexagod** [comment]
<h3> Travis logs </h3> <pre> Event:pull_request <br/> ID:209156521 <br/> Job Number:14.2 <br/> VSnapLink:https://i.imgur.com/1Ct7BuV.png </pre> <br/>

**Comment by rexagod** [comment]
<h3> Travis logs </h3> <pre> Event:pull_request <br/> ID:209157049 <br/> Job Number:16.1 <br/> VSnapLink:https://i.imgur.com/2kKTXBd.png </pre> <br/>

**Comment by rexagod** [comment]
<h3> Travis logs </h3> <pre> Event:pull_request <br/> ID:547531716 <br/> Job Number:32.1 <br/> VSnapLink:https://i.imgur.com/omPaGyF.png </pre> <br/>

**Comment by rexagod** [comment]
<h3> Travis logs </h3> <pre> Event:pull_request <br/> ID:547531717 <br/> Job Number:32.2 <br/> VSnapLink:https://i.imgur.com/KMTJHE7.png </pre> <br/>

**Comment by rexagod** [comment]
<h3> Travis logs </h3> <pre> Event:pull_request <br/> ID:209157050 <br/> Job Number:16.2 <br/> VSnapLink:https://i.imgur.com/04us71H.png </pre> <br/>

**Comment by rexagod** [comment]
@jywarren This will now work for any PR to `ci-ops` branch, as shown above. Once `ci-ops` has been merged to `main` this will work for it as well. Details: https://github.com/publiclab/matcher-cli/pull/5/checks

**Comment by jywarren** [comment]
OK, this is cool - can you write in the docs OR in the comments that it posts, explaining what we're seeing in these screenshots? Like, how will someone coming here know what they're looking at, or if it's good or bad? Thanks Pranshu!!!

**Comment by jywarren** [comment]
And also, although I see https://travis-ci.com/publiclab/matcher-cli/jobs/209157049, it's not clear to me if the `orb-core: processing...` that I see in the screenshot is ALSO running in the Travis jobs, or what relation these have to each other. I think it's important that people be able to see your tests running in text, as well! And that it be clear what they're doing (explain this -- to a newcomer!) and what is "success", you know? Thank you!

**Comment by IgorWilbert** [comment]
@rexagod great work, thank you! I agree with Jeff, it may help others in the future quite a lot. May I help you in any way?

**Comment by rexagod** [comment]
<h3> Travis logs </h3> <pre> Event:pull_request <br/> ID:214860773 <br/> Job Number:18.1 <br/> VSnapLink:https://i.imgur.com/MgfhTqB.png </pre> <br/>

**Comment by rexagod** [comment]
<h3> Travis logs </h3> <pre> Event:pull_request <br/> ID:556885626 <br/> Job Number:34.1 <br/> VSnapLink:https://i.imgur.com/caFmcJN.png </pre> <br/>

**Comment by rexagod** [comment]
<h3> Travis logs </h3> <pre> Event:pull_request <br/> ID:214860774 <br/> Job Number:18.2 <br/> VSnapLink:https://i.imgur.com/FyEuWZL.png </pre> <br/>

**Comment by rexagod** [comment]
<h3> Travis logs </h3> <pre> Event:pull_request <br/> ID:556885627 <br/> Job Number:34.2 <br/> VSnapLink:https://i.imgur.com/lIoAxDj.png </pre> <br/>

**Comment by rexagod** [comment]
<h3> Travis logs </h3> <pre> Event:pull_request <br/> ID:556887124 <br/> Job Number:36.2 <br/> VSnapLink:https://i.imgur.com/V5nB1ui.png </pre> <br/>

**Comment by jywarren** [comment]
Oh whoa, we were in the PR, just commenting on the commits within it! Sorry, I'd just never seen that approach to commenting before. Thanks!

**Comment by jywarren** [comment]
So, i don't quite understand here, does this PR represent new code? Why is it a "Mock PR"? Sorry @rexagod i just am having some trouble understanding your workflow... can you explain what's going on here? Thanks!

**Comment by jywarren** [comment]
I think perhaps it's a good idea to think of a general workflow of:

1. write an issue describing a function or problem or goal to address
2. open a PR with code that addresses the issue

That makes it a lot easier for others to follow what you're doing, you know? Thanks for all your hard work, @rexagod, I think it's really cool! I'm just trying to provide some input on your workflow to help it be more readable to others!

**Comment by rexagod** [comment]
> Why is it a "Mock PR"?

@jywarren This one was to demo the m-cli integration into travis for automated builds as I showcased a while back in the opencall.

Sure thing, I'll do [this](https://github.com/publiclab/matcher-cli/pull/5#issuecomment-510239110) more frequently here now! Thanks!

**Pull request closed without merging**
